/**
 * @file    engine/effect_names.h
 * @brief   Labels for the effect type id space, generated by
 *          tools/gen_effect_names.py from the dev comments in
 *          database/SkEf.u16. Do not edit by hand. The mapping is inferred
 *          from row comments rather than from engine code, so callers show
 *          the raw id beside the label.
 * @copyright Copyright (c) 2026 Tom Clay <tomc@tctechstuff.com>
 *            All rights reserved.
 * @license   BSD 3-Clause License
 *            See LICENSE file in the project root for full license text.
 */
// Labels for the effect type id space, generated by
// tools/gen_effect_names.py from the dev comments in database/SkEf.u16.

#pragma once

#include <rex/types.h>

namespace bd::engine {

// Null for a type with no known label.
inline const char *EffectTypeLabel(u32 type) {
  switch (type) {
  case 0:
    return "damage";
  case 1:
    return "MP drain";
  case 3:
    return "inflict status";
  case 4:
    return "evade and damage reduction";
  case 6:
    return "sleep resistance";
  case 7:
    return "kelolon resistance";
  case 8:
    return "dizzy resistance";
  case 9:
    return "poison resistance";
  case 10:
    return "paralyze resistance";
  case 11:
    return "paralyze barrier";
  case 12:
    return "panic and stink resistance";
  case 13:
    return "petrify resistance";
  case 14:
    return "stun resistance";
  case 15:
    return "status resistance";
  case 16:
    return "knockdown and element nullify";
  case 17:
    return "fire resistance";
  case 18:
    return "water resistance";
  case 19:
    return "earth resistance";
  case 20:
    return "wind resistance";
  case 21:
    return "attack up";
  case 22:
    return "defense up";
  case 23:
    return "hit rate up";
  case 24:
    return "evade up";
  case 25:
    return "magic attack up";
  case 26:
    return "magic defense up";
  case 27:
    return "vitality";
  case 28:
    return "mentality";
  case 34:
    return "existence rule";
  case 35:
    return "guard";
  case 36:
    return "mode change";
  case 37:
    return "dispel";
  case 38:
    return "stream";
  case 40:
    return "scripted action";
  case 44:
    return "steal";
  case 45:
    return "life steal";
  case 46:
    return "removal";
  case 47:
    return "row change";
  case 48:
    return "cooldown reset";
  case 49:
    return "resistance toggle";
  case 53:
    return "materialize";
  case 55:
    return "judgment light";
  case 56:
    return "HP regen";
  case 57:
    return "MP regen";
  default:
    return nullptr;
  }
}

} // namespace bd::engine
