#!/usr/bin/env python3
"""Bake effect type labels from the game's own data.

Emits src/engine/effect_names.h. Run it by hand when the mapping changes and
commit the result.

    python tools/gen_effect_names.py <database-dir> src/engine/effect_names.h

<database-dir> is the extracted database/ directory holding SkEf.u16, a
headerless UTF-16BE CSV. Column 2 is the effect type and column 1 is the
developers' Japanese comment for that row. Those comments are the only naming
source for the type space, so LABELS below is hand-authored from reading them
and this script only checks it against what the table actually contains.

The labels are advisory. The mapping is inferred from row comments rather than
from engine code, which is why callers show the raw id beside the label.
"""
import argparse
import collections
import pathlib

# Hand-authored from the row comments for each type. A type absent here is
# emitted with no label and shows as its raw number.
LABELS = {
    0: "damage",
    1: "MP drain",
    3: "inflict status",
    4: "evade and damage reduction",
    6: "sleep resistance",
    7: "kelolon resistance",
    8: "dizzy resistance",
    9: "poison resistance",
    10: "paralyze resistance",
    11: "paralyze barrier",
    12: "panic and stink resistance",
    13: "petrify resistance",
    14: "stun resistance",
    15: "status resistance",
    16: "knockdown and element nullify",
    17: "fire resistance",
    18: "water resistance",
    19: "earth resistance",
    20: "wind resistance",
    21: "attack up",
    22: "defense up",
    23: "hit rate up",
    24: "evade up",
    25: "magic attack up",
    26: "magic defense up",
    27: "vitality",
    28: "mentality",
    34: "existence rule",
    35: "guard",
    36: "mode change",
    37: "dispel",
    38: "stream",
    40: "scripted action",
    44: "steal",
    45: "life steal",
    46: "removal",
    47: "row change",
    48: "cooldown reset",
    49: "resistance toggle",
    53: "materialize",
    55: "judgment light",
    56: "HP regen",
    57: "MP regen",
}

HEADER = """/**
 * @file    engine/effect_names.h
 * @brief   Labels for the effect type id space, generated by
 *          tools/gen_effect_names.py from the dev comments in
 *          database/SkEf.u16. Do not edit by hand.
 *
 *          These are advisory. The mapping is inferred from row comments rather
 *          than from engine code, so callers show the raw id beside the label.
 *
 * @copyright Copyright (c) 2026 Tom Clay <tomc@tctechstuff.com>
 *            All rights reserved.
 * @license   BSD 3-Clause License
 *            See LICENSE file in the project root for full license text.
 */
#pragma once

#include <rex/types.h>

namespace bd::engine {

// Null for a type with no known label.
inline const char *EffectTypeLabel(u32 type) {
  switch (type) {
"""

FOOTER = """  default:
    return nullptr;
  }
}

} // namespace bd::engine
"""


def rows(path):
    text = path.read_bytes().decode("utf-16-be").replace("﻿", "")
    for line in text.replace("\r", "").split("\n"):
        if line.strip():
            yield line.split(",")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("database", type=pathlib.Path)
    ap.add_argument("out", type=pathlib.Path)
    args = ap.parse_args()

    seen = collections.Counter()
    for table in ("SkEf.u16", "SkEf_new.u16"):
        path = args.database / table
        if not path.exists():
            print(f"{table}: not found, skipped")
            continue
        for r in rows(path):
            if len(r) > 2 and r[2].lstrip("-").isdigit():
                seen[int(r[2])] += 1

    if not seen:
        raise SystemExit("no effect types found, check the database directory")

    unlabeled = sorted(t for t in seen if t not in LABELS)
    if unlabeled:
        print("types in the table with no label: " +
              ", ".join(f"{t} (x{seen[t]})" for t in unlabeled))
    unused = sorted(t for t in LABELS if t not in seen)
    if unused:
        print("labels for types absent from the table: " +
              ", ".join(str(t) for t in unused))

    body = "".join(
        f'  case {t}:\n    return "{LABELS[t]}";\n' for t in sorted(LABELS))
    args.out.write_text(HEADER + body + FOOTER, encoding="utf-8", newline="\n")
    print(f"wrote {args.out} with {len(LABELS)} labels "
          f"covering {sum(seen[t] for t in LABELS if t in seen)} "
          f"of {sum(seen.values())} rows")


if __name__ == "__main__":
    main()
